# Generated by Django 4.1.5 on 2023-01-22 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('padarias', '0006_padaria_cestas_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True, help_text='Data de início da assinatura', verbose_name='Data de início')),
                ('observacao', models.TextField(blank=True, help_text='Observação da assinatura', null=True, verbose_name='Observação')),
                ('cesta', models.OneToOneField(help_text='Cesta da assinatura', on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='padarias.cesta', verbose_name='Cesta')),
                ('user', models.OneToOneField(help_text='Usuário da assinatura', on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
