version: "3.8"
services:
    rpyc_server:
        build: ./server 
        ports: 
            - "18811:18811"
    rpyc_client:
        build: ./client
        volumes:
            - "./client/:/code"
        depends_on:
            - "rpyc_server"
