# Generated by Django 4.1.5 on 2023-01-15 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0002_padaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do produto', null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=10, verbose_name='Preço')),
                ('categoria', models.ForeignKey(help_text='Categoria do produto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='padarias.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
