# Generated by Django 4.1.5 on 2023-01-16 03:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0003_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome da cesta', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da cesta', null=True, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço da cesta', max_digits=10, verbose_name='Preço')),
                ('produtos', models.ManyToManyField(help_text='Produtos da cesta', related_name='cestas', to='padarias.produto', verbose_name='Produtos')),
            ],
        ),
    ]
