# Generated by Django 4.2.4 on 2023-08-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padarias', '0007_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(blank=True, help_text='Nome da categoria', max_length=100, null=True, verbose_name='Descricao'),
        ),
    ]
